### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by imilos** [ColinIanKing/faultstat#1]
Great tool! I did an initial packaging for Fedora, RHEL and CentOS at https://copr.fedorainfracloud.org/coprs/mivanovic/faultstat/. Please review and include `.spec` file if you're interested.

**Comment by ColinIanKing** [comment]
Thanks for the feedback, glad to see it's in Fedora/RHEL+CentoOS!  Can you provide this as a merge request and I'll add it to the repository.
