### ISSUE TITLE
arrows show up as ~F~Q in the snap package

### ISSUE THREAD

**Issue by mgedmin** [ColinIanKing/faultstat#2]
1. sudo snap install faultstat
2. faultstat -T
3. press 'a'

result:

![Ekrano nuotrauka iš 2019-08-14 13-45-04](https://user-images.githubusercontent.com/159967/63015515-d091ca80-be99-11e9-8c5d-ddf10ee65d75.png)

**Comment by mgedmin** [comment]
This looks like the sort of a problem you get if you accidentally link against libncurses instead of libncursesw, but this is not the case:

```
$ ldd /snap/faultstat/current/usr/bin/faultstat
	linux-vdso.so.1 (0x00007ffdfe542000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffa7f622000)
	libncursesw.so.5 => not found
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007ffa7f5f6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa7f40b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffa7f795000)
```

(/snap/faultstat/current/usr/lib/x86_64-linux-gnu/libncursesw.so exists, my ldd just doesn't know how to find it.)

It also shouldn't be a locale problem:
```
$ locale charmap
UTF-8
```

**Comment by ColinIanKing** [comment]
Rather than using fancy chars that don't appear on some consoles, I've replaced the arrows with ASCII '^' (up) and 'v' (down). I've pushed the change to the repo.
